version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: medusa-starter-default
      POSTGRES_USER: kcat
      POSTGRES_PASSWORD: 123123
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
