name: Terraform

on:
  push:
    branches:
      - main  # Replace with your target branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var "upstash_email=${{ secrets.UPSTASH_EMAIL }}" -var "upstash_api_key=${{ secrets.UPSTASH_API_KEY }}" -var "render_api_key=${{ secrets.RENDER_API_KEY }}" -var "render_owner_id=${{ secrets.RENDER_OWNER_ID }}"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'  # Only apply on the main branch
        run: terraform apply -auto-approve -var "upstash_email=${{ secrets.UPSTASH_EMAIL }}" -var "upstash_api_key=${{ secrets.UPSTASH_API_KEY }}" -var "render_api_key=${{ secrets.RENDER_API_KEY }}" -var "render_owner_id=${{ secrets.RENDER_OWNER_ID }}"

